var GUESTS = {
  "ADMIN":{nom:"Admin",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "ADRIEN2027":{nom:"Adrien",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "ALINA2027":{nom:"Alina",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "AMBARTN2027":{nom:"Naza AMBARTSONOVA",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "ANGOTG2027":{nom:"Gabrielle ANGOT",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "ARMAND2027":{nom:"Armand",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "AUBERTE2027":{nom:"Estelle AUBERT",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "AUBERTO2027":{nom:"Olivier AUBERT",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "BAKTHAB2027":{nom:"Bilel BAKTHA",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "BAUDIMG2027":{nom:"Goulven BAUDIMANT",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "BERTRAL2027":{nom:"Louise BERTRAND",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "BOOLUCP2027":{nom:"Paul BOOLUCK",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "BURANOE2027":{nom:"Elisabeth BURANOVSKA",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "BURANOM2027":{nom:"Marian BURANOVSKY",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "BURANOS2027":{nom:"Stefan BURANOVSKY",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "CLAUDOC2027":{nom:"Clémence CLAUDON",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "COPINEAIME2027":{nom:"Copine Aimé",genre:"F",vip:false,etapes:[]},
  "COPINEJORDAN2027":{nom:"Copine Jordan",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "COUBARC2027":{nom:"Christophe COUBARD",genre:"M",vip:true,etapes:["vendredi","eglise","cocktail","brunch"]},
  "COUBARC20272":{nom:"Constance COUBARD",genre:"F",vip:true,etapes:["vendredi","eglise","cocktail","brunch"]},
  "COUBARM2027":{nom:"Maximilien COUBARD",genre:"M",vip:true,etapes:["vendredi","eglise","cocktail","brunch"]},
  "COUBARM20272":{nom:"Malaurie COUBARD",genre:"F",vip:true,etapes:["eglise","cocktail"]},
  "COUBARS2027":{nom:"Séverine COUBARD",genre:"F",vip:true,etapes:["vendredi","eglise","cocktail","brunch"]},
  "COUBARS20272":{nom:"Stéphane COUBARD",genre:"M",vip:true,etapes:["eglise","cocktail"]},
  "DANNY2027":{nom:"Danny",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "DIOUNOJ2027":{nom:"Jordan DIOUNOU",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "DOUMENY2027":{nom:"Yoann DOUMEN",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "GAMBUTE2027":{nom:"Elliot GAMBUT",genre:"M",vip:false,etapes:["eglise","cocktail","brunch"]},
  "GIANNIL2027":{nom:"Leonidas GIANNIKAS",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "GINTZA2027":{nom:"Alena GINTZ",genre:"F",vip:true,etapes:["vendredi","eglise","cocktail","brunch"]},
  "GINTZA20272":{nom:"Amélie GINTZ",genre:"F",vip:true,etapes:["vendredi","eglise","cocktail","brunch"]},
  "GINTZA20273":{nom:"Amandine GINTZ",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "GINTZC2027":{nom:"Christophe GINTZ",genre:"M",vip:true,etapes:["vendredi","eglise","cocktail","brunch"]},
  "GINTZC20272":{nom:"Christianne GINTZ",genre:"F",vip:true,etapes:[]},
  "GINTZJ2027":{nom:"Joëlle GINTZ",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "GINTZL2027":{nom:"Laurence GINTZ",genre:"F",vip:true,etapes:["eglise","cocktail","brunch"]},
  "GINTZL20272":{nom:"Linda GINTZ",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "GINTZL20273":{nom:"Laurie GINTZ",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "GINTZM2027":{nom:"Michel GINTZ",genre:"M",vip:true,etapes:[]},
  "GINTZM20272":{nom:"Marc GINTZ",genre:"M",vip:true,etapes:["eglise","cocktail","brunch"]},
  "GINTZR2027":{nom:"Romain GINTZ",genre:"M",vip:true,etapes:["vendredi","eglise","cocktail","brunch"]},
  "GINTZR20272":{nom:"Régis GINTZ",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "GINTZV2027":{nom:"Vincent GINTZ",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "GINTZV20272":{nom:"Victoriane GINTZ",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "GLAUDEJ2027":{nom:"Jonathan GLAUDE",genre:"M",vip:false,etapes:[]},
  "GLAUDEJ20272":{nom:"Jacqueline GLAUDE",genre:"F",vip:false,etapes:[]},
  "GRISEVL2027":{nom:"Leya GRISEVIC",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "HADJARI2027":{nom:"Isack HADJAR",genre:"M",vip:false,etapes:[]},
  "HAROA2027":{nom:"Alexandre HARO",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "HILDV2027":{nom:"Valérie HILD",genre:"F",vip:false,etapes:["eglise","cocktail","brunch"]},
  "JANSSEC2027":{nom:"Cacotte JANSSENS",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "JANSSEM2027":{nom:"Marco JANSSENS",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "JAUERNL2027":{nom:"Luke JAUERNIG",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "JOURNOD2027":{nom:"Dany JOURNOT",genre:"F",vip:false,etapes:["eglise","cocktail","brunch"]},
  "KAYEMBA2027":{nom:"Audrey KAYEMBE",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "KIEFFEJ2027":{nom:"Jean-Marc KIEFFER",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "KIEFFEM2027":{nom:"Marie KIEFFER",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "LEA2027":{nom:"Léa",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "LORENTC2027":{nom:"Clément LORENTE",genre:"M",vip:false,etapes:[]},
  "LORENTC20272":{nom:"Charles LORENTE",genre:"M",vip:false,etapes:[]},
  "LORENTG2027":{nom:"Gisèle LORENTE",genre:"F",vip:false,etapes:[]},
  "LORENTH2027":{nom:"Hugues LORENTE",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "LORENTS2027":{nom:"Salvador LORENTE",genre:"M",vip:false,etapes:[]},
  "LUCILE2027":{nom:"Lucile",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "MAGALHL2027":{nom:"Luis MAGALHAES",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "MARION2027":{nom:"Marion",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "MARJORIE2027":{nom:"Marjorie",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "MENSAHC2027":{nom:"Claude MENSAH",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "MENSAHG2027":{nom:"Guy MENSAH",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "MENSAHG20272":{nom:"Giresse MENSAH",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "MENSAHM2027":{nom:"Mickael MENSAH",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "MENSAHM20272":{nom:"Maéva MENSAH",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "MENSAHP2027":{nom:"Pauline MENSAH",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "MENSAHT2027":{nom:"Théo MENSAH",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "MESLINA2027":{nom:"Antoine MESLIN",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "MESLINA20272":{nom:"Adrien MESLIN",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "MESLINT2027":{nom:"Thierry MESLIN",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "MESLINV2027":{nom:"Valérie MESLIN",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "MEYERG2027":{nom:"Gilbert MEYER",genre:"M",vip:false,etapes:[]},
  "MEYERJ2027":{nom:"Jeanne MEYER",genre:"F",vip:false,etapes:[]},
  "MIZENKD2027":{nom:"Dodo MIZENKO",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "NEITERL2027":{nom:"Loanne NEITER",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "NOEMIE2027":{nom:"Noémie",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "OSSEC2027":{nom:"Céline OSSÉ",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "OSSEP2027":{nom:"Pascale OSSÉ",genre:"F",vip:false,etapes:[]},
  "OSSES2027":{nom:"Stéphanie OSSÉ",genre:"F",vip:false,etapes:[]},
  "OSSES20272":{nom:"Sidney OSSÉ",genre:"M",vip:false,etapes:[]},
  "RAISONA2027":{nom:"Alain RAISON",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "RASANAM2027":{nom:"Marjorie RASANAYAGAM",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "ROHALM2027":{nom:"Milan ROHAL",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "SAOCORA2027":{nom:"Aimé SAO-CORDIEZ",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "STOLLE2027":{nom:"Eliane STOLL",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "STOLLJ2027":{nom:"Jackie STOLL",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "TAASS2027":{nom:"Sudey TAAS",genre:"F",vip:false,etapes:["eglise","cocktail"]},
  "TKACOVJ2027":{nom:"Jozef TKACOVY",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "TKACOVM2027":{nom:"Marta TKACOVA",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail"]},
  "VAILLAM2027":{nom:"Marie-France VAILLANT",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "VIEYRAC2027":{nom:"Charles VIEYRA",genre:"M",vip:false,etapes:["eglise","cocktail"]},
  "VUILLEL2027":{nom:"Laure VUILLEMIN",genre:"F",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]},
  "ZINCKG2027":{nom:"Gaspard ZINCK",genre:"M",vip:false,etapes:["vendredi","eglise","cocktail","brunch"]}
};

var TEMOINS = {
  "ZINCKG2027": "Gaspard, mon temoin depuis toujours, merci d'etre a mes cotes ce jour-la comme dans tous les autres.",
  "NEITERL2027": "Loanne, ma temoin et complice de toujours, hate de partager ce jour avec toi.",
  "GRISEVL2027": "Leya, merci d'etre une des demoiselles d'honneur de Lea, on t'attend avec impatience."
};